#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# blockMeshDict.m4 is missing for this case?
#m4 constant/polyMesh/blockMeshDictAxi.m4 > constant/polyMesh/blockMeshDict
runApplication blockMesh
runApplication solids4FoamAW

# ----------------------------------------------------------------- end-of-file

