#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

m4 constant/polyMesh/blockMeshDictAxi.m4 > constant/polyMesh/blockMeshDict
runApplication blockMesh
#runApplication changeDictionary
runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

