#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Run solver
runApplication solids4Foam
#runApplication decomposePar -force
#runParallel solidFoam 8
#runApplication reconstructPar
